### ISSUE TITLE
Read current height

### ISSUE THREAD

**Issue by loryanstrant** [C-Lock/desk_control#2]
What do you think it would take to read the current height of the desk?
I had the manufacturer send me some info a while ago that may have useful programming references, but it doesn't mean a huge amount to me, so I'd be happy to share those.
Unfortunately I'm no dev (only a bit of YAML, JSON and HTML here and there), but happy to help with what I can.

**Comment by C-Lock** [comment]
That's a great question. It's been a while since I looked at it, but one of the available commands the bluetooth connection offers yields a large quantity of information. It's mostly gibberish, but it's got some info like the serial number, model, firmware version, etc.

I'm certain some of the gibberish has got to be settings. 
I'll dust off the black hat and snoop some more bluetooth today.

**Comment by C-Lock** [comment]
There is absolutely no change in the data it yields.
What info did you get from the manufacturer? I'd like to take a look at that.

**Comment by loryanstrant** [comment]
Ah that's super disappointing.
Here's the info I got from the manufacturer in conversation with them mid last year. I just had a look through and I'm not sure how useful it'll be: https://strant-my.sharepoint.com/:f:/p/loryan/EuqUpmNRy09NqRlCdGcyy7cBXuwON3Qbrgmeeqrwly0zpw?e=WHJhgw

Also there's this repo, where in it he mentions "monitor", but I'm no dev so I can't really tell if in the code it has anything about actually reading the current height.

**Comment by C-Lock** [comment]
Ok, I've added a file, [hex_crazyness](https://github.com/C-Lock/desk_control/blob/main/hex_crazyness)
This isn't so much "dev" work as it is "What drugs were the devs on?" detective work.
If you have a chance to take a look, and want to riddle out some meaning from a myriad of hex values... please do.

When we write  characteristic we use handler 0x0025 to do so, and we receive a response on 0x0028.

From previous reconnaisance, I know these handlers also have descriptions.
0x0025 = Data In
0x0028 = Data Oute

```
handle: 0x0025, uuid: 0000ff01-0000-1000-8000-00805f9b34fb #!
handle: 0x0026, uuid: 00002901-0000-1000-8000-00805f9b34fb # Data In
handle: 0x0027, uuid: 00002803-0000-1000-8000-00805f9b34fb # 10 28 00 02 ff
handle: 0x0028, uuid: 0000ff02-0000-1000-8000-00805f9b34fb #!
handle: 0x0029, uuid: 00002902-0000-1000-8000-00805f9b34fb # 01 00
handle: 0x002a, uuid: 00002901-0000-1000-8000-00805f9b34fb # Data Out
handle: 0x002b, uuid: 00002803-0000-1000-8000-00805f9b34fb #0a 2c 00 03 ff
```

When moving the desk, there is absolutely no other communication between the client/server.
There is, however, a large amount of general chatter which I haven't even begun to look at.

Here is an example of moving the desk down a bit

```
[my:blt:addr][LE]> char-write-req 0x0025 f1f10200027e
Characteristic value was written successfully
Notification handle = 0x0028 value: f2 f2 01 03 01 1d 03 25 7e
Notification handle = 0x0028 value: f2 f2 01 03 01 1c 03 24 7e
Notification handle = 0x0028 value: f2 f2 01 03 01 1b 03 23 7e
Notification handle = 0x0028 value: f2 f2 01 03 01 19 03 21 7e
```

Since there's no other communication at the time, but the app knows the height at any given time, there are two possibilities
1. The App is guessing.
2. The response is the height

I'm inclined to think it's the second option.
Data beginning with `f1f1` is to the device, `f2f2` is from the device. `01 03` is on all `f2f2` communications, and `7e` terminates all communications.

This leaves only 4 hex values in each response packet for the height to be conveyed.
i.e. `f2 f2 01 03 01 1d 03 25 7e` breaks into
Prefix: ` f2 f2 01 03`
Data : `01 1d 03 25`
Suffix: `7e`

The first hex in the data section is always either `00` or `01` and it swaps over at approximately 64cm going up.
64cm is an awfully suspect number for a hex based system.  This leads me to believe that our increment is .25cm

So, anything under 64cm (64*4 = 256 = ff) will start with `00` and anything over 64cm will start with `01`
Next up, we notice that the second hex is ALSO incrementing by almost 1, the third hex is ALWAYS `03`, and then the 4th hex increments by almost 1.

Now, we have a small problem, the app only gives us integer values for height. This makes the 4th hex value...annoying.
BUT, I do have a general rule of thumb. I have to do math later to figure out like, boundary conditions.
Let's say you want the desk at 68cm
68 > 64, so we're gonna need that initial `01`
68 * 4 = 272
272 - 256 = 16
hex(16) = 10
so our 'data' should show between `01 10 03 ??` and `01 13 03 ??` according to my predictions.

The app says my desk is currently at 65cm
Here, is the latest `0x0028` response:
`Notification handle = 0x0028 value: f2 f2 01 03 01 01 03 09 7e`
`01 01 03 09` 
`01` means start with 256, 
`01` means add 1,
`09` means ?$%$
so, we take out 257 and divide it by 4, and we have 64.25. 
Once we figure out how that `09` modifies the values, I suspect we'll have a number which rounds nicely to 65cm.

I'll have to keep working on it, though, as that 4th hex value is a mystery atm.
Gotta get out my lasermeter to precisely measure the height after modifications and do some math to figure out how the last hex affects the readings.

If you have time to look over the recent file upload, please do.

**Comment by C-Lock** [comment]
> Ah that's super disappointing. Here's the info I got from the manufacturer in conversation with them mid last year. I just had a look through and I'm not sure how useful it'll be: https://strant-my.sharepoint.com/:f:/p/loryan/EuqUpmNRy09NqRlCdGcyy7cBXuwON3Qbrgmeeqrwly0zpw?e=WHJhgw
> 
> Also there's this repo, where in it he mentions "monitor", but I'm no dev so I can't really tell if in the code it has anything about actually reading the current height.

What repo?

The `communication protocol.pdf` file looks relevant, it describes that there are 8 data bits, then a stop bit.
The stop bit is `7e`, but I can't figure the rest out this late at night.

**Comment by loryanstrant** [comment]
Sorry, I forgot to put the link in for the repo: https://github.com/jakllsch/py-bleedesk-demo

**Comment by loryanstrant** [comment]
That's awesome progress, thanks!
I'll have a crack at it tomorrow after my daughter's birthday party, keen to see what I can get out of it.

**Comment by C-Lock** [comment]
## Findings
Ok, so my hunch was correct.
The response data is almost exactly the height.
The app ALWAYS ROUNDS UP.    61.1 becomes 62 when the app displays the data.
As for the physical movement, one "up" movement from my scripts is approximately 1.1cm. 

From measurements using a laser, I was able to determine that the value returned by the bluetooth was always off from my measurements by a mostly consistent value, ~5cm. This roughly equates to the height of my meter. So, that's the height!

I've added 2 files, a json wil measurements, notification handlers, and app readings from a whole bunch of height modifications.

Second, I added [interpret_hex.py](https://github.com/C-Lock/desk_control/blob/main/interpret_hex.py) 
This one just does some mathy stuff real quick and I found that the previously mentioned calculation is super correct.
We just need an offset for stuff like thickness of desktop and if you're on carpet. 

The fourth hex is still curious, but I did not need to use it to make accurate predictions/calculations based on the return values.

## Next Steps
Now I just need to figure out how to get the response data inside code.
In both shell and python I have seen the response printed out, but I haven't successfully captured it into a variable.
I just need to master that, and I should be able to update the code to return the new height whenever a modification is made.

**Comment by C-Lock** [comment]
New branch, new code.

https://github.com/C-Lock/desk_control/tree/read_height
#Altered Files
desk_control.py

# Features
desk_control.py now has new features:
  * New commands have been added to decrease reliance on the app or physical controls
    *   `mon` , short for monitor, will query the desk for current height without making modification
    *   `save1` will save the current settings into the 'sit' memory
    *   `save2` will save the current settings into the 'stand' memory
    *   `stop` is unknown. I found it when comparing my commands to another [repo](https://github.com/jakllsch/py-bleedesk-demo/blob/master/bleedesk.py). While our commands are identical, that repo has an additional command. I haven't tested it.
 * New Monitoring Function:
    *  Sending any command to the system will now also try to output the current height. 
    *  It's still testing. I've found that for long operations (ex: from sit to stand) stop caring about 5 seconds in and provide current height instead of final height.

## Next steps
This change only affects the python version.
While in bash I was able to see the 0x0028 responses in gatttool, I have not yet successfully received them inside a script.
Next stop should be updating the bash script with at the very least a query.

**Comment by loryanstrant** [comment]
Mate, this is absolutely legendary - thank you!
I'll switch to using the Python version and see how I go.

Again, thank you!

**Comment by loryanstrant** [comment]
I'm getting this error when trying it. Any ideas?
![image](https://user-images.githubusercontent.com/51473494/176785626-f564fc6e-b6b0-4b27-a8f6-e11c0ffbae89.png)

Sit & stand commands work fine. Just not the monitor.

**Comment by C-Lock** [comment]
Is this happening consistently, occasionally, or once?

I think that'd be related to the following bit of code:

```
        while len(self.response_array) > array_len0: #The response values arrive asynchronosly, in the background. The main process threads on (DO NOT PARDON THAT PUN)
            #print(array_len0)                        #This loop tries (and fails) to ensure the responses have stopped arriving before we grab the final height
            array_len0=len(self.response_array)
            sleep(2)
        if len(self.response_array):
            self.height=self.return_height(self.response_array[-1]) #Use the final response to gauge height
            #print(self.height)
            return self.height
```

The main problem here is that the 'response' values which contain the height don't return like a typical variable, I've got to set a listener in the background, and then the desk sends constant data output to it, which is sometimes just blank lines.

It looks like maybe the last data output it received before sending was a blank line, ergo 'out of range'.

**Comment by loryanstrant** [comment]
Always errors out unfortunately. :-(

**Comment by loryanstrant** [comment]
The height readings are way off too:
![image](https://user-images.githubusercontent.com/51473494/176976164-3dbbf212-988d-4d9d-9a7f-1463865eb9d1.png)
